spring:
  profiles:
    active: secret, common

---

spring.config.activate.on-profile: common

server:
  port: 8096

spring:
  security:
    user:
      name: admin
      password: admin
  data:
    rest:
      basePath: /api
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  main:
    banner-mode: "off"
  application:
    name: withNuri

  # ? MariaDB ??
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/condb
    username: conuser
    password: 12345

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none

## ? JWT ??
#jwt:
#  secret: mySuperSecretKeyForJwtTokenAuthenticationAndValidation1234
#  expiration: 86400000  # 24?? (1?)

# ? ?? ??
logging:
  level:
    org:
      thymeleaf: DEBUG
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# ? Swagger UI ???
springdoc:
  swagger-ui:
    enabled: true

# ? PortOne ?? API ?? (???)
portone:
  secret_key: your_secret_key_here
  api:
    url: https://api.portone.io/v2

kakaocert:
  #링크아이디
  linkId: TESTER
  #비밀키
  secretKey: SwWxqU+0TErBXy/9TVjIPEnI0VTUMMSQZtJf3Ed8q3I=
  #이용기관코드 (파트너 사이트에서 확인가능)
  clientCode: '023040000001'
  #인증토큰 IP 검증 설정, ture-사용, false-미사용, (기본값:true)
  isIpRestrictOnOff: true
  #통신 고정 IP, true-사용, false-미사용, (기본값:false)
  useStaticIp: false